<script lang="ts">
	import { onMount } from 'svelte';
	import jsPDF from 'jspdf';
	import 'katex/dist/katex.css';
	import 'carta-md/default.css';
	import type { ProblemDisplayViewDto } from '$services/gen-client';
	import { publicApi } from '$services/apiService';
	import { Button } from 'flowbite-svelte';
	import ProblemComponent from '$components/ui/ProblemComponent.svelte';
	import MarkdownDisplay from '$components/ui/MarkdownDisplay.svelte';

	let skfList: string[] = [];
	let problems: ProblemDisplayViewDto[] = [];
	let html2pdf: any;
	let pdfTitle = 'Užduotys';
	let includeLink = true;
	let printAnswers = false;
	let windowLocation: string | null = null;

	onMount(async () => {
		html2pdf = await import('html2pdf.js').then((module) => module.default);

		const urlParams = new URLSearchParams(window.location.search);
		const listValue = urlParams.get('list') || '';
		skfList = listValue.split(',').map((item) => `SKF-${item}`);
		const problemPromises = skfList.map((skfCode) => publicApi.getProblemBySkfCode(skfCode));
		const problemResponses = await Promise.all(problemPromises);
		problems = problemResponses.map((response) => response.data);

		// Accessing window only after component has been mounted
		windowLocation = window.location.href.slice(8);
	});

	async function downloadPdf(isAnswers = false) {
		if (isAnswers) {
			printAnswers = true;
		} else {
			printAnswers = false;
		}
		window.print();
	}

	function addSkfItem() {
		skfList = [...skfList, `SKF-`];
		updateUrl();
	}

	function updateSkfItem(index: number, e: Event) {
		const value = (e.target as HTMLInputElement).value;
		skfList[index] = value;
		updateUrl();
	}

	function removeSkfItem(index: number) {
		skfList = skfList.filter((_, i) => i !== index);
		updateUrl();
	}

	function updateUrl() {
		const queryParams = new URLSearchParams(window.location.search);
		queryParams.set('list', skfList.map((item) => item.replace('SKF-', '')).join(','));
		const newUrl = `${window.location.pathname}?${queryParams.toString()}`;
		history.replaceState(null, '', newUrl);
		windowLocation = window.location.href.slice(8);
	}

	function reloadPage() {
		window.location.reload();
	}
</script>

<div class="no-print">
	<h1 class="text-4xl font-semibold my-4 text-center">Atrinktų užduočių sąrašas</h1>
	{#if problems.length > 0}
		{#each problems as problem, i}
			<div>
				<h2>{i + 1}.</h2>
				<ProblemComponent
					problemMainData={{
						skfCode: problem.skfCode === '' ? problem.id : problem.skfCode,
						problemText: problem.problemText,
						problemImageSrc: problem.problemImageSrc,
						answerText: problem.answerText,
						answerImageSrc: problem.answerImageSrc,
						categories: problem.categories,
						sourceId: problem.sourceId
					}}
				/>
			</div>
		{/each}
		<div class="md:w-1/2 flex flex-col m-auto gap-2 my-4">
			<label for="pdftitle" class="block mb-2">PDF pavadinimas</label>
			<input id="pdftitle" type="text" bind:value={pdfTitle} class="w-full p-2 mb-4" />
			<div class="flex flex-row gap-2">
				<input type="checkbox" bind:checked={includeLink} />
				<p>Pridėti nuorodą, t.y. užduočių numerių sąrašą</p>
			</div>
			<Button color="blue" on:click={() => downloadPdf(false)}>Atsisiųsti užduočių PDF</Button>
			<Button color="yellow" on:click={() => downloadPdf(true)}>Atsisiųsti atsakymų PDF</Button>
		</div>
	{:else}
		<p>Nėra užduočių</p>
	{/if}
</div>

<div class={`${printAnswers ? 'hidden' : ''}`}>
	<div class="hidden only-print">
		{#if problems.length > 0}
			<div class="flex flex-col flex-1 relative">
				<h4 class="text-center">{pdfTitle}</h4>
				{#each problems as problem, i}
					<MarkdownDisplay
						value={(i + 1).toString() +
							'\\. ' +
							problem.problemText +
							(problem.problemImageSrc.length > 0
								? `\n\n<!---The text below is autogenerated. It is amended during runtime--->\n![Užduoties ${problem.skfCode} paveikslėlis](${problem.problemImageSrc})`
								: '')}
					/>
				{/each}
			</div>

			<div class="flex flex-col flex-1">
				<h4 class="text-center">{pdfTitle}</h4>
				{#each problems as problem, i}
					<MarkdownDisplay
						value={(i + 1).toString() +
							'\\. ' +
							problem.problemText +
							(problem.problemImageSrc.length > 0
								? `\n\n<!---The text below is autogenerated. It is amended during runtime--->\n![Užduoties ${problem.skfCode} paveikslėlis](${problem.problemImageSrc})`
								: '')}
					/>
				{/each}
			</div>
		{:else}
			<p>Nėra užduočių</p>
		{/if}
		<div class="fixed bottom-0 right-2 text-[8px]">
			{includeLink ? windowLocation : 'Sugeneruota bankas.skafis.lt'}
		</div>
		<div class="fixed bottom-0 right-[50%] text-[8px]">
			{includeLink ? windowLocation : 'Sugeneruota bankas.skafis.lt'}
		</div>
	</div>
</div>

<div class={`${printAnswers ? '' : 'hidden'}`}>
	<div class="hidden only-print">
		{#if problems.length > 0}
			<div class="flex flex-col flex-1 relative">
				<h4 class="text-center">{pdfTitle} (atsakymai)</h4>
				{#each problems as problem, i}
					<MarkdownDisplay
						value={(i + 1).toString() +
							'\\. ' +
							problem.answerText +
							(problem.answerImageSrc.length > 0
								? `\n\n<!---The text below is autogenerated. It is amended during runtime--->\n![Užduoties ${problem.skfCode} paveikslėlis](${problem.answerImageSrc})`
								: '')}
					/>
				{/each}
			</div>

			<div class="flex flex-col flex-1 relative">
				<h4 class="text-center">{pdfTitle} (atsakymai)</h4>
				{#each problems as problem, i}
					<MarkdownDisplay
						value={(i + 1).toString() +
							'\\. ' +
							problem.answerText +
							(problem.answerImageSrc.length > 0
								? `\n\n<!---The text below is autogenerated. It is amended during runtime--->\n![Užduoties ${problem.skfCode} paveikslėlis](${problem.answerImageSrc})`
								: '')}
					/>
				{/each}
			</div>
		{:else}
			<p>Nėra užduočių</p>
		{/if}
		<div class="fixed bottom-0 right-2 text-[8px]">
			{includeLink ? windowLocation : 'Sugeneruota bankas.skafis.lt'}
		</div>
		<div class="fixed bottom-0 right-[50%] text-[8px]">
			{includeLink ? windowLocation : 'Sugeneruota bankas.skafis.lt'}
		</div>
	</div>
</div>

<div class="no-print">
	<h1 class="text-4xl font-semibold my-4 text-center">SKF sąrašas</h1>
	{#if skfList.length > 0}
		<ul class="list-disc list-inside">
			{#each skfList as skf, index}
				<li>
					<input
						type="text"
						bind:value={skf}
						on:input={(e) => updateSkfItem(index, e)}
						class="p-1 border-b border-gray-400 focus:outline-none"
					/>
					<Button color="red" on:click={() => removeSkfItem(index)}>Remove</Button>
				</li>
			{/each}
		</ul>
		<Button on:click={addSkfItem} class="mt-2">Add Item</Button>
	{:else}
		<p>Nėra sąrašo</p>
	{/if}
	<Button on:click={reloadPage} color="red">Reload Page</Button>
</div>
