<script lang="ts">
	import { Card } from 'flowbite-svelte';
	import ProblemMeta from './ProblemMeta.svelte';
	import type { Components } from '../../types';
	import MarkdownDisplay from './MarkdownDisplay.svelte';

	export let problemMainData: Components.ProblemMainData;
</script>

<Card class="min-w-full">
	<div class="flex flex-col relative">
		<h2 class="text-xl font-bold text-left">{problemMainData.skfCode}</h2>
		<ProblemMeta categoryId={problemMainData.categoryId} sourceId={problemMainData.sourceId} />
		{#if problemMainData.problemText || problemMainData.problemImageSrc.length > 0}
			<MarkdownDisplay
				value={problemMainData.problemText +
					(problemMainData.problemImageSrc.length > 0
						? `\n\n<!---The text below is autogenerated. It is amended during runtime--->\n![Užduoties ${problemMainData.skfCode} paveikslėlis](${problemMainData.problemImageSrc})`
						: '')}
			/>
		{/if}

		{#if problemMainData.answerText || problemMainData.answerImageSrc.length > 0}
			<details>
				<summary class="text-right">Žr. atsakymą</summary>
				<p><strong>Atsakymas:</strong></p>
				<MarkdownDisplay
					value={problemMainData.answerText +
						(problemMainData.answerImageSrc.length > 0
							? `\n\n<!---The text below is autogenerated. It is amended during runtime--->\n![Užduoties ${problemMainData.skfCode} atsakymo paveikslėlis](${problemMainData.answerImageSrc})`
							: '')}
				/>
			</details>
		{:else}
			<p class="text-right">Atsakymas nėra pateiktas</p>
		{/if}
	</div>
</Card>
