<script lang="ts">
	import { Card, Checkbox } from 'flowbite-svelte';
	import ProblemMeta from './ProblemMeta.svelte';
	import type { Components } from '../../types';
	import MarkdownDisplay from './MarkdownDisplay.svelte';
	import { getContext } from 'svelte';

	export let problemMainData: Components.ProblemMainData;
	const { appendItemToList, removeItemFromList, isInList } = getContext<any>('skfList');
</script>

<Card class="min-w-full">
	<div class="flex flex-col relative">
		<h2 class="text-xl font-bold text-left">{problemMainData.skfCode}</h2>
		<ProblemMeta categories={problemMainData.categories} sourceId={problemMainData.sourceId} />
		{#if problemMainData.problemText || problemMainData.problemImageSrc.length > 0}
			<MarkdownDisplay
				value={problemMainData.problemText +
					(problemMainData.problemImageSrc.length > 0
						? `\n\n<!---The text below is autogenerated. It is amended during runtime--->\n![Užduoties ${problemMainData.skfCode} paveikslėlis](${problemMainData.problemImageSrc})`
						: '')}
			/>
		{/if}
		<div class="flex justify-end">
			{#if problemMainData.skfCode.substring(0, 4) === 'SKF-'}
				<Checkbox
					checked={isInList(problemMainData.skfCode)}
					on:change={() => {
						if (isInList(problemMainData.skfCode)) {
							removeItemFromList(problemMainData.skfCode);
						} else {
							appendItemToList(problemMainData.skfCode);
						}
					}}
				>
					Pridėti prie &nbsp;<a href="/list">sąrašo</a>
				</Checkbox>
			{/if}
		</div>
		{#if problemMainData.answerText || problemMainData.answerImageSrc.length > 0}
			<details>
				<summary class="w-fit ml-auto">Žr. atsakymą</summary>
				<p><strong>Atsakymas:</strong></p>
				<MarkdownDisplay
					value={problemMainData.answerText +
						(problemMainData.answerImageSrc.length > 0
							? `\n\n<!---The text below is autogenerated. It is amended during runtime--->\n![Užduoties ${problemMainData.skfCode} atsakymo paveikslėlis](${problemMainData.answerImageSrc})`
							: '')}
				/>
			</details>
		{:else}
			<p class="text-right">Atsakymas nėra pateiktas</p>
		{/if}
	</div>
</Card>
