<script lang="ts">
	import { Card, Checkbox } from 'flowbite-svelte';
	import ProblemMeta from './ProblemMeta.svelte';
	import type { Components } from '../../types';
	import MarkdownDisplay from '$components/forms/MarkdownDisplay.svelte';
	import { getContext } from 'svelte';
	import { ProblemDisplayViewDtoProblemVisibilityEnum } from '$services/gen-client';

	export let problemMainData: Components.ProblemMainData;
	export let canList = true;
	const { appendItemToList, removeItemFromList, isInList } = getContext<any>('skfList');
</script>

<Card class="min-w-full card">
	<div class="flex flex-col relative">
		<p class="text-sm font-bold text-left">{problemMainData.skfCode}</p>
		<ProblemMeta categories={problemMainData.categories} sourceId={problemMainData.sourceId} />
		{#if problemMainData.visibility === ProblemDisplayViewDtoProblemVisibilityEnum.Visible}
			{#if problemMainData.problemText || problemMainData.problemImageSrc.length > 0}
				<MarkdownDisplay
					value={problemMainData.problemText +
						(problemMainData.problemImageSrc.length > 0
							? `\n\n<!---The text below is autogenerated. It is amended during runtime--->\n![Užduoties ${problemMainData.skfCode} paveikslėlis](${problemMainData.problemImageSrc})`
							: '')}
				/>
			{/if}
			<div class="flex justify-end">
				{#if canList}
					<Checkbox
						class="transform scale-125 mr-2"
						checked={isInList(problemMainData.skfCode)}
						on:change={() => {
							if (isInList(problemMainData.skfCode)) {
								removeItemFromList(problemMainData.skfCode);
							} else {
								appendItemToList(problemMainData.skfCode);
							}
						}}
					></Checkbox>
					<div class="text-sm text-black">Pridėti prie &nbsp;<a href="/list">sąrašo</a></div>
				{/if}
			</div>
			{#if problemMainData.answerText || problemMainData.answerImageSrc.length > 0}
				<details>
					<summary class="w-fit ml-auto">Žr. atsakymą</summary>
					<p><strong>Atsakymas:</strong></p>
					<MarkdownDisplay
						value={problemMainData.answerText +
							(problemMainData.answerImageSrc.length > 0
								? `\n\n<!---The text below is autogenerated. It is amended during runtime--->\n![Užduoties ${problemMainData.skfCode} paveikslėlis](${problemMainData.answerImageSrc})`
								: '')}
					/>
				</details>
			{:else}
				<p class="text-right">Atsakymas nėra pateiktas</p>
			{/if}
		{:else if problemMainData.visibility === ProblemDisplayViewDtoProblemVisibilityEnum.NotExisting}
			<p class="text-center">❌ Užduotis su tokiu kodu neegzistuoja ❌</p>
		{:else if problemMainData.visibility === ProblemDisplayViewDtoProblemVisibilityEnum.Hidden}
			<p class="text-center">
				🔒 Ši užduotis Jums neprieinama. Bandykite prisijungti arba naudokite kitą paskyrą 🔒
			</p>
		{:else}
			<p class="text-center">Šito teksto neturėtumėte matyti. Susisiekite su administratoriumi</p>
		{/if}
	</div>
</Card>
